### ISSUE TITLE
Unable to Deploy - Repeatable - Problem with Custom Resource

### ISSUE THREAD

**Issue by rpattcorner** [aws-samples/public-file-browser-for-amazon-s3#8]
The application repeatedly won't deploy for me.  All goes well until the Custom::SeedS3Data, which fails with the message below.  I've checked the lambda, which does indeed exist, but creates no cloudwatch logs to examine.  

CREATE_FAILED                Custom::SeedS3Data           SeedS3Data                   CloudFormation did not     
                                                                                       receive a response from    
                                                                                       your Custom Resource.      
                                                                                       Please check your logs for 
                                                                                       requestId [1ed80...02bea0f].   
                                                                                       If you are using the       
                                                                                       Python cfn-response        
                                                                                       module, you may need to    
                                                                                       update your Lambda         
                                                                                       function code so that      
                                                                                       CloudFormation can attach  
                                                                                       the updated version.      

Other aspects of the deploy appear to have been successful.

1. Could you please advise me on debugging suggestions?
2. It appears that there are two stacks in the initial deploy ... an `aws-sam-cli-managed-default` stack which CREATE_COMPLETE that appears to persist across deploy attempts, and a `public-file-browser` stack that is created (and must be tediously manually destroyed` with each deploy attempt.  In debugging should I remove both stacks between attempts, or just the newly created one?
3. My understanding is that the fail is on the lambda response that triggers stack completion.  It looks like all the lambda work is just to populate the files bucket, which I'm quite happy to do by hand for the research purposes I'm carrying out.  Do you have any suggestions for simply eliminating the file upload stage so I can examine a working deploy?
4. I was surprised that bucket destruction wasn't blocking successive runs, as CFN used to do.  Should I be manually destroying the buckets anyway between attempts?

One last note ... I made some efforts to implement, test and research the main.js application, and found that there seemed to be an asynchronous call problem in listing the files bucket, where the creds from the Cognito Identity call arrived *after* the call to ListBucketsV2.  Has that been a problem in past?

**Comment by ckabalan** [comment]
@rpattcorner, this looks like it might be a duplicate of #5 .

Did you follow the deployment instructions step-by-step, including the prerequisites and notably the "sam build" step? I suspect just like in #5, the issue is the Custom Resource doesn't have the `crhelper` library to report status back to CloudFormation.

1 - Usually CloudWatch Logs would be the best approach, but...
2 - The default stack is for SAM to upload the templates and Lambda ZIPs, so yes persists across deployments and stacks, it's a staging ground for SAM, non-specific to any deployment. Just delete the public-file-browser stack.
3 - You could comment out the Custom::SeedS3Data resource in the template, but does two things: modifies the website files to be specific to your bucket, and uploads them to S3. You'd have to look at the code and reverse engineer the entries in the index.html file.
4 - Up to you. The buckets are uniquely named based on stack-id (intentionally to prevent this), and persisted even when the stack is deleted because we don't want customers to accidentally lose data.

On your last note, I've never seen this. I'll double check the code again but this should happen in sequence.

If you do still have issues please report back with a full copy-paste of your commands to SAM (start to finish) so I can double check there isn't anything I'm not considering from memory.

**Comment by rpattcorner** [comment]
Thanks.  Definitely did the SAM build.  Here's what I see from my end (mildly redacted).  The deploy will sit in its current state, waiting for that custom resource. 

**$ ~/bin/aws-sam/sam build**
Building codeuri:                                                                                                   
[localpathstuff]/sam/seed_s3_data runtime: python3.11 metadata: {'cfn_nag': {'rules_to_suppress':   
[{'id': 'W89', 'reason': 'This does not increase the security of the solutions and greatly increases the cost and   
scope of the deployment.'}, {'id': 'W92', 'reason': 'This is not necessary for this function as it is only executed 
during CloudFormation deployment and not related to end-user requests.'}]}, 'checkov': {'skip': [{'id':             
'CKV_AWS_173', 'comment': 'Environment variables do not contain sensitive data.'}, {'id': 'CKV_AWS_117', 'comment': 
'This does not increase the security of the solutions and greatly increases the cost and scope of the deployment.'},
{'id': 'CKV_AWS_115', 'comment': 'Concurrency limit does not make sense for a Lambda Backed Custom Resource only    
used during stack deployment'}, {'id': 'CKV_AWS_116', 'comment': 'DLQ does not make sense for a Lambda Backed Custom
Resource only used during stack deployment'}]}} architecture: arm64 functions: CustomSeedS3Data                     
 Running PythonPipBuilder:ResolveDependencies                                                                       
 Running PythonPipBuilder:CopySource                                                                                

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {{stack-name}} --watch
[*] Deploy: sam deploy --guided

**The deploy** (intermediate successful notifications removed for brevity.  Will not return, will time out in hours)

$ ~/bin/aws-sam/sam deploy --guided --capabilities CAPABILITY_NAMED_IAM --profile myprofile --region us-west-2

Configuring SAM deploy
======================

        Looking for config file [samconfig.toml] :  Not found

        Setting default arguments for 'sam deploy'
        =========================================
        Stack Name [sam-app]: public-file-browser-5
        AWS Region [us-west-2]: 
        Parameter SiteName [AnyCompany Public Files]: Test 5
        Parameter FilesOpenTabMode [In New Tab]: 
        Parameter VisibleStorageClasses [STANDARD,STANDARD_IA,ONEZONE_IA,REDUCED_REDUNDANCY]: 
        Parameter CrossOriginRestriction [*]: 
        #Shows you resources changes to be deployed and require a 'Y' to initiate deploy
        Confirm changes before deploy [y/N]: 
        #SAM needs permission to be able to create roles to connect to the resources in your template
        Allow SAM CLI IAM role creation [Y/n]: 
        #Preserves the state of previously provisioned resources when an operation fails
        Disable rollback [y/N]: 
        Save arguments to configuration file [Y/n]: 
        SAM configuration file [samconfig.toml]: samconfig5.toml
        SAM configuration environment [default]: 

        Looking for resources needed for deployment:

        Managed S3 bucket: aws-sam-cli-managed-default-samclisourcebucket-xxxxxxx
        A different default S3 bucket can be set in samconfig.toml and auto resolution of buckets turned off by setting resolve_s3=False

        Saved arguments to config file
        Running 'sam deploy' for future deployments will use the parameters saved above.
        The above parameters can be changed by modifying samconfig.toml
        Learn more about samconfig.toml syntax at 
        https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html

        Uploading to public-file-browser-5/dxxxxxxxxxx  15242985 / 15242985  (100.00%)

        Deploying with following values
        ===============================
        Stack name                   : public-file-browser-5
        Region                       : us-west-2
        Confirm changeset            : False
        Disable rollback             : False
        Deployment s3 bucket         : aws-sam-cli-managed-default-samclisourcebucket-xxx
        Capabilities                 : ["CAPABILITY_NAMED_IAM"]
        Parameter overrides          : {"SiteName": "Test 5", "FilesOpenTabMode": "In New Tab", "VisibleStorageClasses": "STANDARD,STANDARD_IA,ONEZONE_IA,REDUCED_REDUNDANCY", "CrossOriginRestriction": "*"}
        Signing Profiles             : {}

Initiating deployment
=====================

        Uploading to public-file-browser-5/xxxxxxx.template  25039 / 25039  (100.00%)


Waiting for changeset to be created..

CloudFormation stack changeset
-----------------------------------------------------------------------------------------------------------------
Operation                    LogicalResourceId            ResourceType                 Replacement                
-----------------------------------------------------------------------------------------------------------------
+ Add                        CloudFrontOriginAccessCont   AWS::CloudFront::OriginAcc   N/A                        
                             rol                          essControl                                              
+ Add                        CloudFront                   AWS::CloudFront::Distribut   N/A                        
                                                          ion                                                     
+ Add                        CognitoIdentityPoolRoleMap   AWS::Cognito::IdentityPool   N/A                        
                             ping                         RoleAttachment                                          
+ Add                        CognitoIdentityPool          AWS::Cognito::IdentityPool   N/A                        
+ Add                        CognitoIdentityUnauthentic   AWS::IAM::Role               N/A                        
                             atedRole                                                                             
+ Add                        CustomSeedS3DataRole         AWS::IAM::Role               N/A                        
+ Add                        CustomSeedS3Data             AWS::Lambda::Function        N/A                        
+ Add                        LoggingBucketBucketPolicy    AWS::S3::BucketPolicy        N/A                        
+ Add                        LoggingBucket                AWS::S3::Bucket              N/A                        
+ Add                        PublicFilesBucketBucketPol   AWS::S3::BucketPolicy        N/A                        
                             icy                                                                                  
+ Add                        PublicFilesBucket            AWS::S3::Bucket              N/A                        
+ Add                        PublicWebsiteBucketBucketP   AWS::S3::BucketPolicy        N/A                        
                             olicy                                                                                
+ Add                        PublicWebsiteBucket          AWS::S3::Bucket              N/A                        
+ Add                        SeedS3Data                   Custom::SeedS3Data           N/A                        
-----------------------------------------------------------------------------------------------------------------


Changeset created successfully. arn:aws:cloudformation:us-west-2:999999999999:changeSet/samcli-deploy99999-9999-9999-999999


2024-05-03 15:57:13 - Waiting for stack create/update to complete

CloudFormation events from stack operations (refresh every 5.0 seconds)
-----------------------------------------------------------------------------------------------------------------
ResourceStatus               ResourceType                 LogicalResourceId            ResourceStatusReason       
-----------------------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS           AWS::CloudFormation::Stack   public-file-browser-5        User Initiated             
CREATE_IN_PROGRESS           AWS::S3::Bucket              LoggingBucket                -                          
**...Lots of CREATE_COMPLETE successes**                         
          
CREATE_COMPLETE              AWS::S3::Bucket              PublicWebsiteBucket          -                          
**CREATE_IN_PROGRESS           Custom::SeedS3Data           SeedS3Data                   -**                          
CREATE_IN_PROGRESS           AWS::CloudFront::Distribut   CloudFront                   -                          
                             ion                                                                                  
CREATE_IN_PROGRESS           AWS::CloudFront::Distribut   CloudFront                   Resource creation          
                             ion                                                       Initiated                  
CREATE_COMPLETE              AWS::CloudFront::Distribut   CloudFront                   -                          
                             ion                                                                                  
CREATE_IN_PROGRESS           AWS::S3::BucketPolicy        PublicWebsiteBucketBucketP   -                          
                                                          olicy                                                   
CREATE_IN_PROGRESS           AWS::S3::BucketPolicy        PublicFilesBucketBucketPol   -                          
                                                          icy                                                     
CREATE_IN_PROGRESS           AWS::S3::BucketPolicy        PublicFilesBucketBucketPol   Resource creation          
                                                          icy                          Initiated                  
CREATE_COMPLETE              AWS::S3::BucketPolicy        PublicFilesBucketBucketPol   -                          
                                                          icy                                                     
CREATE_IN_PROGRESS           AWS::S3::BucketPolicy        PublicWebsiteBucketBucketP   Resource creation          
                                                          olicy                        Initiated                  
CREATE_COMPLETE              AWS::S3::BucketPolicy        PublicWebsiteBucketBucketP   -                          
                                                          olicy     

(will time out in a few hours)

**Comment by rpattcorner** [comment]
Definitely built, but no solution.  Rewrote.
